## Exceções (#2)

Escreva uma função chamada `abort()` que recebe um parâmetro `String` e então lança um objeto `Exception` simples, passando o argumento de `abort()` para o construtor de `Exception`. Em `main()`, chame `abort()` com um argumento de `"Pare!"` e use `capture` para verificar o resultado.